Adding Paging functionality + sort
fmhy/maliciouscompliance pull request #2
Opened 2023-09-04 16:22 UTC by AlexTurff

Added logic to page post requests to retrieve the entire post history. Added "Old" sort to ensure chronological order

2023-09-05 04:20 UTC, taskylizard requested changes

2023-09-05 04:20 UTC, taskylizard commented on migrate.py
> -            old_com, limit=int(config["Community Migration"]["limit"])
Remove this from config.ini.example if we won't use it anymore.

2023-09-05 04:20 UTC, taskylizard commented on migrate.py
Mistype probably but two `break`s for?

2023-09-05 21:11 UTC, AlexTurff commented on migrate.py
> -            old_com, limit=int(config["Community Migration"]["limit"])
Done

2023-09-05 21:11 UTC, AlexTurff commented on migrate.py
Done

2023-09-06 03:19 UTC, taskylizard approved these changes

2023-09-06 03:20 UTC, merged

2023-09-06 03:20 UTC, taskylizard commented
Thanks for the PR!